import photo1 from "../assets/images/photo1.png";
import photo2 from "../assets/images/photo2.png";
import stack from "../assets/images/stack.png";
import calendar from "../assets/images/calendar.png";
import comment from "../assets/images/comment.png";
import notes from "../assets/images/notes.png";
import upload from "../assets/images/upload.png";

const userData = [
  {
    title: "Incomplete",
    backgroundColor: "bg-red-700",
    count: 0,
    cardDetails: [
      {
        leftProImg: photo1,
        leftProTitle: "Client name 11",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },
    ],
  },

  // Todo
  {
    title: "Todo",
    backgroundColor: "bg-blue-500",
    count: 0,
    cardDetails: [
      {
        leftProImg: photo1,
        leftProTitle: "Client name 11",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },
    ],
  },

  // doing
  {
    title: "Doing",
    backgroundColor: "bg-yellow-300",
    count: 0,
    cardDetails: [
      {
        leftProImg: photo1,
        leftProTitle: "Client name 11",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },
    ],
  },
  //Under review
  {
    title: "Under review",
    count: 0,
    cardDetails: [
      {
        leftProImg: photo1,
        leftProTitle: "Client name 11",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },
    ],
  },
  // completed
  {
    title: "Completed",
    count: 0,
    cardDetails: [
      {
        leftProImg: photo1,
        leftProTitle: "Client name 11",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },

      {
        leftProImg: photo1,
        leftProTitle: "Client name",
        rightProImg: photo2,
        rightProTitle: "sadik istiak",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, aspernatur?",
        note: "1/2",
        downProleft: photo1,
        downProRight: photo2,
        seen: 12,
        comment: 15,
        upload: 25,
        date: "30-12-2022",
      },
    ],
  },

  //
];

export default userData;
